# Generated by Django 6.0.3 on 2026-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('terms_and_conditions', 'Terms & Conditions'), ('shipping_policy', 'Shipping Policy'), ('refund_and_return', 'Refund & Return'), ('privacy_policy', 'Privacy Policy'), ('cookie_policy', 'Cookie Policy'), ('disclaimer', 'Disclaimer')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_audit_date', models.DateField()),
                ('compliance_score', models.PositiveIntegerField(default=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
