# Generated by Django 6.0.3 on 2026-04-10 15:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='category_image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
    ]
